spring.application.name=ba-backend-spring-cognito

server.port=8081

spring.datasource.url=jdbc:h2:mem:cognitodb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

aws.region=eu-central-1
aws.cognito.userPoolId=eu-central-1_QuhDlcGXQ
aws.cognito.clientId=2p1c8sb12boir1dkid42sfc5bh
aws.cognito.clientSecret=156hgqe0kk252qlmquao74h46sfotisj26fohihe2g58uittbofb
aws.cognito.jwksUri=https://cognito-idp.${aws.region}.amazonaws.com/${aws.cognito.userPoolId}/.well-known/jwks.json
aws.cognito.issuerUri=https://cognito-idp.${aws.region}.amazonaws.com/${aws.cognito.userPoolId}

spring.security.oauth2.resourceserver.jwt.issuer-uri=${aws.cognito.issuerUri}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${aws.cognito.jwksUri}

logging.level.root=INFO
logging.level.fh.babackendspringcognito=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n

metrics.security.lines-of-code.enabled=true
metrics.time-to-first-token.enabled=true
metrics.coupling.enabled=true

